-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 11:28:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Appareil de Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appareil de Test` (
  `idAppareil` INT NOT NULL,
  `Numero_de_version` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAppareil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gestionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestionnaire` (
  `Identifiant` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  `Telephone` INT NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Identifiant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Sexe` VARCHAR(45) NOT NULL,
  `Date_de_naissance` DATE NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Mot_de_passe` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `Gestionnaire_Identifiant` INT NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  INDEX `fk_Utilisateur_Gestionnaire1_idx` (`Gestionnaire_Identifiant` ASC),
  CONSTRAINT `fk_Utilisateur_Gestionnaire1`
    FOREIGN KEY (`Gestionnaire_Identifiant`)
    REFERENCES `mydb`.`Gestionnaire` (`Identifiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrateur` (
  `idAdministrateur` INT NOT NULL,
  `Informations_de_contact` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test` (
  `idtest` INT NOT NULL,
  `Type_de_test` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Heure` TIME NOT NULL,
  PRIMARY KEY (`idtest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appareil_de_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appareil_de_test` (
  `idReference` INT NOT NULL,
  `Numero_de_version` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resultat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Resultat` (
  `idResultat` INT NOT NULL,
  `Score` INT NOT NULL,
  `test_idtest` INT NOT NULL,
  `Appareil_de_test_idReference` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  INDEX `fk_Résultat_test1_idx` (`test_idtest` ASC),
  PRIMARY KEY (`idResultat`),
  INDEX `fk_Resultat_Appareil_de_test1_idx` (`Appareil_de_test_idReference` ASC),
  INDEX `fk_Resultat_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Résultat_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `mydb`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultat_Appareil_de_test1`
    FOREIGN KEY (`Appareil_de_test_idReference`)
    REFERENCES `mydb`.`Appareil_de_test` (`idReference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultat_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQ` (
  `idFAQ` INT NOT NULL,
  `Question` TINYTEXT NOT NULL,
  `Réponse` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idFAQ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Capteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Capteur` (
  `idCapteur` INT NOT NULL,
  `Type_de_capteur` VARCHAR(45) NOT NULL,
  `Appareil_de_test_idReference` INT NOT NULL,
  `test_idtest` INT NOT NULL,
  PRIMARY KEY (`idCapteur`),
  INDEX `fk_Capteur_Appareil_de_test1_idx` (`Appareil_de_test_idReference` ASC),
  INDEX `fk_Capteur_test1_idx` (`test_idtest` ASC),
  CONSTRAINT `fk_Capteur_Appareil_de_test1`
    FOREIGN KEY (`Appareil_de_test_idReference`)
    REFERENCES `mydb`.`Appareil_de_test` (`idReference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Capteur_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `mydb`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sujet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sujet` (
  `idSujet` INT NOT NULL,
  `Titre_sujet` VARCHAR(200) NOT NULL,
  `Corps` TEXT(6) NULL,
  `Date` DATE NOT NULL,
  `Heure` TIME NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idSujet`),
  INDEX `fk_Sujet_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Sujet_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reponse` (
  `idmessage` INT NOT NULL,
  `texte` TINYTEXT NOT NULL,
  `date_et_heure` DATETIME(6) NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Sujet_idSujet` INT NOT NULL,
  PRIMARY KEY (`idmessage`),
  INDEX `fk_reponse_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_reponse_Sujet1_idx` (`Sujet_idSujet` ASC),
  CONSTRAINT `fk_reponse_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_Sujet1`
    FOREIGN KEY (`Sujet_idSujet`)
    REFERENCES `mydb`.`Sujet` (`idSujet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
